### ISSUE TITLE
Edit and delete icons, or an ellipses

### ISSUE THREAD

**Issue by JacobJenness** [UMM-CSci-3601-S21/it-2-it-2-chicken#22]
Should there be separate buttons for deleting and editing a word, or should it be condensed into an ellipses button?

**Comment by RichardLussier** [comment]
It's been decided to have separate buttons for deleting and editing words

**Comment by lam00071** [comment]
The issue has been reviewed and answered by KK. For now, we don't have a lot of interaction with a word besides edit and delete word, leaving 2 icons for 2 button options instead of a droplist is good for now. (We only sold the delete word feature but we also included the edit icon button to show how they will be displayed).
